[Rainmeter]
Update=-1
DynamicWindowSize=1
OnRefreshAction=[!Enablemeasure HiddenWindow][!EnableMeasure HideGame]

[Variables]
@include=#@#GamesInfo.inc
@include2=#@#NonSteamGames.inc
@include3=#@#SkinInfo.inc
FirstGame=2
EntrySize=21
ActiveConfig="SteamyRain.ini"
Vis0=0
Egame0Vis=0
YPLUS=0
HiddenListY=20
HiddenListHidden=0
@include4=#@#extraMeters\HiddenList.inc

;_________________________________________________
;____________________MEASURES_____________________
[SettingCheck]
Measure=Calc
IfCondition=#Mode#=0
IfCondition2=(#Mode#=0) && (#Settings#=1)
IfCondition3=(#Mode#=1) && (#Settings#=1)
IfTrueAction=[!SetVariable XPLUS "(#TilePixels#+1)"][!SetVariable YPLUS "-125"]
IfTrueAction2=[!SetVariable XPLUS "(#TilePixels#+1)"][!SetVariable YPLUS "-17"]
IfTrueAction3=[!SetVariable XPLUS "(#TilePixels#+1)"]

[TilePixelsY]
Measure=Calc
Formula=((#TilePixels#*46.74)/100)+#YPLUS#
DynamicVariables=1

[ModeCheck]
Measure=Calc
IfCondition=#Mode#=0
IfTrueAction=[!Setvariable ActiveConfig "SteamyRainList.ini"][!EnableMeasure MoveWindow][!UpdateMeasure MoveWindow][!ReDraw]
IfFalseAction=[!EnableMeasure MoveWindow][!UpdateMeasure MoveWindow][!ReDraw]
DynamicVariables=1

[MoveWindow]
Measure=Calc
OnUpdateAction=[!Move "(#SkinPosX#+#XPLUS#)" "(#SkinPosY#+[TilePixelsY]+20)"]
DynamicVariables=1
Disabled=1

;_________________________________________________
;__________________HOST CHROME____________________
[HeaderContainer]
Meter=Shape
Shape=Rectangle 0,0,225,20,6 | Fill Color #Dark1# | StrokeWidth 0 | Scale #Container#,1,0,0
Shape2=Rectangle 0,10,225,(Clamp((([HiddenGames]*#EntrySize#)+5),41,(#EntrySize#*#VisibleTilesS#+5))) | Fill Color #Dark1# | StrokeWidth 0 | Scale #Container#,#Container#,0,0
Group=HeaderContainer | Scaling | Headerhide
DynamicVariables=1
Hidden=#Header#

[Header]
Meter=Shape
Shape=Rectangle 0,0,225,20,6 | Fill Color #Dark1# | StrokeWidth 0
Shape2=Rectangle 0,10,225,10 | Fill Color #Dark1# | StrokeWidth 0
Shape3=Rectangle 0,20,225,(Clamp((([HiddenGames]*#EntrySize#)+5),41,(#EntrySize#*#VisibleTilesS#+5))) | Fill Color #Dark1# | StrokeWidth 0
DynamicVariables=1
Group=HeaderContainer
Container=HeaderContainer

[HeaderClose]
Meter=Shape
Shape=Rectangle 208,0,19,18,6 | Fill Color #CloseBG# | StrokeWidth 0
Shape2=Rectangle 208,10,19,10 | Fill Color #CloseBG# | StrokeWidth 0
Shape3=Rectangle 208,0,11,18 | Fill Color #CloseBG# | StrokeWidth 0
Container=HeaderContainer
Hidden=1

[Close]
Meter=String
Text="[\xe8bb]"
FontSize=8
MeterStyle=HiddenButtonStyle
LeftMouseUpAction=[!WriteKeyValue Variables hiddenWindow 0 "#@#SkinInfo.inc"][!SetVariable hiddenWindow 0 "SteamyRain" "#ActiveConfig#"][!DeactivateConfig]
MouseOverAction=[!SetOption HeaderClose Hidden 0][!UpdateMeter HeaderClose][!ReDraw]
MouseLeaveAction=[!SetOption HeaderClose Hidden 1][!UpdateMeter HeaderClose][!ReDraw]
Container=HeaderContainer
Y=4
X=210

[Logo]
Meter=Image
PreserveAspectRatio=1
DynamicVariables=1
MouseActionCursor=0
MiddleMouseUpAction=[!DeactivateConfig]
ImageName=#@#img\SteamyRain
Group=Scaling
X=#LogoX#
Y=#LogoY#
H=#LogoSize#

[Title]
Meter=String
FontWeight=600
StringCase=upper
FontSize=8
AntiAlias=1
FontColor=#TextColor#
Text="Hidden Games"
SolidColor=#Dark2#,1
Padding=0,0,0,0
Y=4
X=24

[DEBUG]
Meter=String
MeasureName=HiddenGames
Text="%1#CRLF#GameCountPLUS:#GameCountPLUS##CRLF#ExtraGameCountPLUS:#ExtraGameCountPLUS#"
DynamicVariables=1
FontColor=255,255,255
SolidColor=0,0,0
FontSize=18
Hidden=1
Group=Games
Y=150
